### PR TITLE
Script for setting up a proxy connection to another machine

### PR DESCRIPTION
**Pull request by StayerX**
@CloudwickShared/cloudwick team please review.

### CODE REVIEW

**Comment by bhavintandel** [comment]
@StayerX what does this do ? and where will it be used

**Comment by StayerX** [comment]
I have given all this information in the script header. However I am not going to provide a single use case scenario, since this can be used in many occasions and is not necessarily relevant to Hadoop.

**Comment by StayerX** [comment]
@deepdoradla any thoughts?

**Comment by despoinak1** [comment]
LGTM!

**Comment by deepdoradla** [comment]
hey @StayerX thanks for referring me here ... after getting some hang on it, I might b able to provide more inputs ... for starters Looks good to me too... :)

**Comment by StayerX** [comment]
@derwinmcgeary Do you want to merge this?

**Comment by derwinmcgeary** [comment]
Done!

**Pull request merged**
