### PR TITLE
Stan

### LINKED ISSUE #16: A script that creates all the ssh keys for the users.

### PR DESCRIPTION
**Pull request by StayerX**
Started cleaning the repository. It is still under progress, but I would like to merge it with master to reduce future conflicts. This will also close #16.

### CODE REVIEW

**Comment by StayerX** [comment]
@CloudwickShared/cloudwick How does the initial [structure ](https://github.com/CloudwickShared/Hadoop/tree/stan) look? Any suggestions for the future steps?

**Comment by derwinmcgeary** [comment]
LGTM! :cactus:

**Comment by despoinak1** [comment]
You can merge it.

**Comment by bhavintandel** [comment]
LGTM !

**Pull request merged**
