### PR TITLE
Quick Script for connecting through a tunel to a server. 

### PR DESCRIPTION
**Pull request by StayerX**
Needs automation of password in future.
Also it seems I added versions.sh by mistake too. I suggest we ignore this mistake but make sure it is not repeated.

### CODE REVIEW

**Comment by StayerX** [comment]
@CloudwickShared/cloudwick team please review.

**Comment by bhavintandel** [comment]
i have no idea about tunneling.

**Comment by StayerX** [comment]
@bhavintandel 
If you run this script like this: `./setup_conections.sh bhavin@openstack.cloudwick.com root@172.16.0.126 2222 22` and enter your password you should be able to connect to the server by using `ssh localhost -p 2222`

If you run this script like this: `./setup_conections.sh bhavin@openstack.cloudwick.com root@172.16.0.126 8080 8080` and enter your password you should be able to connect to the website for the next steps of the installation of hadoop in your browser in this way: `http://localhost:8080`

**Comment by bhavintandel** [comment]
@StayerX  gotcha thanks

**Comment by bhavintandel** [comment]
looks okay

**Comment by StayerX** [comment]
@despoinak1 @taffazzel @duhit Any thoughts?

**Comment by despoinak1** [comment]
Why do all variables take the $1 value?

**Comment by StayerX** [comment]
@despoinak1 Because I am applying shift, which makes $2 into $1, $3 into $2 etc..

**Comment by StayerX** [comment]
@derwinmcgeary please review

**Pull request merged**
