### PR TITLE
Latest version Java 1.8.8.51

### PR DESCRIPTION
**Pull request by StayerX**
@CloudwickShared/cloudwick Please review. I will do the merging.

### CODE REVIEW

**Comment by bhavintandel** [comment]
sorry for closing the request, @CloudwickShared/cloudwick pls review

**Comment by StayerX** [comment]
Looks good to me.

**Comment by despoinak1** [comment]
I believe it is ok

**Comment by StayerX** [comment]
@derwinmcgeary do you approve?

**Pull request merged**
