### PR TITLE
Master configuration

### PR DESCRIPTION
**Pull request by despoinak1**
I have added the master_config.sh file for the master node configuration.

### CODE REVIEW

**Comment by StayerX** [comment]
Looks good. Do not merge until the others have finished their part. If you wish continue with another issue.

**Comment by bhavintandel** [comment]
it alright, We need to rename it tough

**Comment by bhavintandel** [comment]
Looks fine to me

**Comment by StayerX** [comment]
@despoinak1 this time we will leave it as is. in the future for a separate issue create a separate branch.

**Pull request merged**
