### PR TITLE
Airlinedata

### PR DESCRIPTION
**Pull request by derwinmcgeary**
This should close issue #44 but we also need to get the data into the correct form.

### CODE REVIEW

**Comment by StayerX** [comment]
LGTM :kimono:

**Comment by bhavintandel** [comment]
Looks cool

**Comment by derwinmcgeary** [comment]
This is now greatly improved - please let's pull it today!

**Comment by StayerX** [comment]
LGreatTM

**Comment by despoinak1** [comment]
LGTM!

**Comment by StayerX** [comment]
@derwinmcgeary great job. I am merging and removing the branch.

**Comment by drhemanth** [comment]
It worked for me thanks Derwin

**Pull request merged**
