### PR TITLE
Remaned install_hortanworks.md -> install_hortonworks.md

### LINKED ISSUE #31: install_hortanworks.md is misspelled
Needs to be renamed to install_hortonworks.md

### PR DESCRIPTION
**Pull request by StayerX**
This pull request will close #31 .
@CloudwickShared/cloudwick please review.

### CODE REVIEW

**Comment by derwinmcgeary** [comment]
LGTM! :cake:

**Comment by StayerX** [comment]
Look good to me too

**Comment by taffazzel** [comment]
Looks good to me

**Comment by drhemanth** [comment]
looks good to me

**Pull request merged**
