### PR TITLE
Fix bug where #! was not line one and add a line to edit ambari-agent.ini

### PR DESCRIPTION
**Pull request by derwinmcgeary**

### CODE REVIEW

**Comment by StayerX** [comment]
I approve, but I believe you changed more than that. (line ending on all lines)

**Comment by derwinmcgeary** [comment]
Well caught: I was trying to track down why it was behaving strangely.

**Comment by StayerX** [comment]
Run: `sed -i -e 's/\r$//'  <file_name>`

**Comment by StayerX** [comment]
@CloudwickShared/cloudwick What do you think guys?

**Comment by bhavintandel** [comment]
is it necessary have to write -y in yum ?

**Comment by StayerX** [comment]
No. But if you want it to execute automatically yes.

**Comment by bhavintandel** [comment]
@StayerX  what do u mean automatic ?

**Comment by StayerX** [comment]
Without the user having to do anything. You run the command and it installs everything without asking for any confirmation from the user.

**Comment by bhavintandel** [comment]
ohh i didn't know that, thanks. Looks cool to me.

**Comment by derwinmcgeary** [comment]
@bhavintandel SELinux commands added!

**Comment by bhavintandel** [comment]
Cool, LGTM

**Pull request merged**
