### PR TITLE
Version based ambari

### PR DESCRIPTION
**Pull request by StayerX**
@CloudwickShared/cloudwick Please review. I will do the merging.

### CODE REVIEW

**Comment by StayerX** [comment]
There are two files changed here. While versionAmbari looks good I do not agree with the other one. Could you remove it from the commit?

**Comment by bhavintandel** [comment]
@StayerX  How can i undo particular commit from here ?

**Comment by StayerX** [comment]
Ignore the problem this time since we have spend too much time on fixing this kind of issues. Lets set up as a goal to have clean commits from now on.

**Comment by despoinak1** [comment]
I believe it is correct.

**Comment by bhavintandel** [comment]
it just download the file, i have to write few lines to install it

**Comment by StayerX** [comment]
@CloudwickShared/cloudwick I fixed the issues and now it can merge with master.

**Pull request merged**
