### PR TITLE
Added a script for automation of the installation of the kerberos

### PR DESCRIPTION
**Pull request by StayerX**
This pull request will close issue #42 
It is ready for review.

### CODE REVIEW

**Comment by StayerX** [comment]
LGTM!

**Comment by derwinmcgeary** [comment]
Sound as a pound!

**Comment by bhavintandel** [comment]
no its bad

**Comment by bhavintandel** [comment]
@StayerX  you can add **-y** so it will install without any administration

**Comment by StayerX** [comment]
This is not something that would work guys. it was just an example of how to create a pull request.

**Comment by StayerX** [comment]
@bhavintandel You are right.

**Pull request closed without merging**
