### PR TITLE
Latest version Java 1.8.8.51

### PR DESCRIPTION
**Pull request by bhavintandel**
I have added script to add latest version of java, @CloudwickShared/cloudwick  pls review

### CODE REVIEW

**Comment by StayerX** [comment]
Looks good to me.

**Comment by StayerX** [comment]
@despoinak1 @taffazzel @duhit  Please review all the pull request so that we can merge.
Everyone must be up to date with what each request does.

**Comment by taffazzel** [comment]
Seems fine.

**Comment by StayerX** [comment]
@taffazzel Please do not close pull request while there are members that have not reviewed.

**Comment by despoinak1** [comment]
I believe it is fine.

**Pull request closed without merging**
